config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :event_users
  resources :event_foundations
  resources :events_users
  resources :foundation_types
  resources :profile_roles
  resources :profiles
  resources :roles
  resources :events
  devise_for :users
  resources :foundations
  get 'users/user'

  get 'admin/users'

  get 'home/index'
  
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_foundation.rb
class EventFoundation < ApplicationRecord
  belongs_to :foundation
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :event_foundation
  belongs_to :user
end

app/models/foundation.rb
class Foundation < ApplicationRecord
  belongs_to :foundation_type
end

app/models/foundation_type.rb
class FoundationType < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/profile_role.rb
class ProfileRole < ApplicationRecord
  belongs_to :role
  belongs_to :profile
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # attr_accessible :email, :password, :password_confirmation, :remember_me, :role_attributes
  has_one :role
  accepts_nested_attributes_for :role  
  
  validates :role_id, presence: true
end

app/controllers/foundations_controller.rb
class FoundationsController < ApplicationController
  before_action :set_foundation, only: [:show, :edit, :update, :destroy]

  # GET /foundations
  # GET /foundations.json
  def index
    @foundations = Foundation.all
  end

  # GET /foundations/1
  # GET /foundations/1.json
  def show
  end

  # GET /foundations/new
  def new
    @foundation = Foundation.new
  end

  # GET /foundations/1/edit
  def edit
  end

  # POST /foundations
  # POST /foundations.json
  def create
    @foundation = Foundation.new(foundation_params)

    respond_to do |format|
      if @foundation.save
        format.html { redirect_to @foundation, notice: 'Foundation was successfully created.' }
        format.json { render :show, status: :created, location: @foundation }
      else
        format.html { render :new }
        format.json { render json: @foundation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foundations/1
  # PATCH/PUT /foundations/1.json
  def update
    respond_to do |format|
      if @foundation.update(foundation_params)
        format.html { redirect_to @foundation, notice: 'Foundation was successfully updated.' }
        format.json { render :show, status: :ok, location: @foundation }
      else
        format.html { render :edit }
        format.json { render json: @foundation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foundations/1
  # DELETE /foundations/1.json
  def destroy
    @foundation.destroy
    respond_to do |format|
      format.html { redirect_to foundations_url, notice: 'Foundation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foundation
      @foundation = Foundation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foundation_params
      params.require(:foundation).permit(:name, :nit, :active, :foundation_type_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :active)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description, :active)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/events_users_helper.rb
module EventsUsersHelper
end

app/helpers/foundation_helper.rb
module FoundationHelper
end

app/helpers/foundations_helper.rb
module FoundationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_roles_helper.rb
module ProfileRolesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foundations/_form.html.erb
<%= form_with(model: foundation, local: true) do |form| %>
  <% if foundation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foundation.errors.count, "error") %> prohibited this foundation from being saved:</h2>

      <ul>
      <% foundation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :foundation_name %>
  </div>

  <div class="field">
    <%= form.label :nit %>
    <%= form.text_field :nit, id: :foundation_nit %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.number_field :active, id: :foundation_active %>
  </div>

  <div class="field">
    <%= form.label :foundation_type_id %>
    <%= form.text_field :foundation_type_id, id: :foundation_foundation_type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foundations/edit.html.erb
<h1>Editing Foundation</h1>

<%= render 'form', foundation: @foundation %>

<%= link_to 'Show', @foundation %> |
<%= link_to 'Back', foundations_path %>

app/views/foundations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foundations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Nit</th>
      <th>Active</th>
      <th>Foundation type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foundations.each do |foundation| %>
      <tr>
        <td><%= foundation.name %></td>
        <td><%= foundation.nit %></td>
        <td><%= foundation.active %></td>
        <td><%= foundation.foundation_type %></td>
        <td><%= link_to 'Show', foundation %></td>
        <td><%= link_to 'Edit', edit_foundation_path(foundation) %></td>
        <td><%= link_to 'Destroy', foundation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foundation', new_foundation_path %>

app/views/foundations/new.html.erb
<h1>New Foundation</h1>

<%= render 'form', foundation: @foundation %>

<%= link_to 'Back', foundations_path %>

app/views/foundations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @foundation.name %>
</p>

<p>
  <strong>Nit:</strong>
  <%= @foundation.nit %>
</p>

<p>
  <strong>Active:</strong>
  <%= @foundation.active %>
</p>

<p>
  <strong>Foundation type:</strong>
  <%= @foundation.foundation_type %>
</p>

<%= link_to 'Edit', edit_foundation_path(@foundation) %> |
<%= link_to 'Back', foundations_path %>