config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :event_users
  resources :event_foundations
  resources :events_users
  resources :foundation_types
  resources :profile_roles
  resources :profiles
  resources :roles
  resources :events
  devise_for :users
  resources :foundations
  get 'users/user'

  get 'admin/users'

  get 'home/index'
  
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_foundation.rb
class EventFoundation < ApplicationRecord
  belongs_to :foundation
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :event_foundation
  belongs_to :user
end

app/models/foundation.rb
class Foundation < ApplicationRecord
  belongs_to :foundation_type
end

app/models/foundation_type.rb
class FoundationType < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/profile_role.rb
class ProfileRole < ApplicationRecord
  belongs_to :role
  belongs_to :profile
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # attr_accessible :email, :password, :password_confirmation, :remember_me, :role_attributes
  has_one :role
  accepts_nested_attributes_for :role  
  
  validates :role_id, presence: true
end

app/controllers/event_users_controller.rb
class EventUsersController < ApplicationController
  before_action :set_event_user, only: [:show, :edit, :update, :destroy]

  # GET /event_users
  # GET /event_users.json
  def index
    @event_users = EventUser.all
  end

  # GET /event_users/1
  # GET /event_users/1.json
  def show
  end

  # GET /event_users/new
  def new
    @event_user = EventUser.new
  end

  # GET /event_users/1/edit
  def edit
  end

  # POST /event_users
  # POST /event_users.json
  def create
    @event_user = EventUser.new(event_user_params)

    respond_to do |format|
      if @event_user.save
        format.html { redirect_to @event_user, notice: 'Event user was successfully created.' }
        format.json { render :show, status: :created, location: @event_user }
      else
        format.html { render :new }
        format.json { render json: @event_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_users/1
  # PATCH/PUT /event_users/1.json
  def update
    respond_to do |format|
      if @event_user.update(event_user_params)
        format.html { redirect_to @event_user, notice: 'Event user was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_user }
      else
        format.html { render :edit }
        format.json { render json: @event_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_users/1
  # DELETE /event_users/1.json
  def destroy
    @event_user.destroy
    respond_to do |format|
      format.html { redirect_to event_users_url, notice: 'Event user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_user
      @event_user = EventUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_user_params
      params.require(:event_user).permit(:event_foundation_id, :user_id, :points, :dateEvent)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description, :active)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/events_users_helper.rb
module EventsUsersHelper
end

app/helpers/foundation_helper.rb
module FoundationHelper
end

app/helpers/foundations_helper.rb
module FoundationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_users/_form.html.erb
<%= form_with(model: event_user, local: true) do |form| %>
  <% if event_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_user.errors.count, "error") %> prohibited this event_user from being saved:</h2>

      <ul>
      <% event_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_foundation_id %>
    <%= form.text_field :event_foundation_id, id: :event_user_event_foundation_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :event_user_user_id %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points, id: :event_user_points %>
  </div>

  <div class="field">
    <%= form.label :dateEvent %>
    <%= form.datetime_select :dateEvent, id: :event_user_dateEvent %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_users/edit.html.erb
<h1>Editing Event User</h1>

<%= render 'form', event_user: @event_user %>

<%= link_to 'Show', @event_user %> |
<%= link_to 'Back', event_users_path %>

app/views/event_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Users</h1>

<table>
  <thead>
    <tr>
      <th>Event foundation</th>
      <th>User</th>
      <th>Points</th>
      <th>Dateevent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_users.each do |event_user| %>
      <tr>
        <td><%= event_user.event_foundation %></td>
        <td><%= event_user.user %></td>
        <td><%= event_user.points %></td>
        <td><%= event_user.dateEvent %></td>
        <td><%= link_to 'Show', event_user %></td>
        <td><%= link_to 'Edit', edit_event_user_path(event_user) %></td>
        <td><%= link_to 'Destroy', event_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event User', new_event_user_path %>

app/views/event_users/new.html.erb
<h1>New Event User</h1>

<%= render 'form', event_user: @event_user %>

<%= link_to 'Back', event_users_path %>

app/views/event_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event foundation:</strong>
  <%= @event_user.event_foundation %>
</p>

<p>
  <strong>User:</strong>
  <%= @event_user.user %>
</p>

<p>
  <strong>Points:</strong>
  <%= @event_user.points %>
</p>

<p>
  <strong>Dateevent:</strong>
  <%= @event_user.dateEvent %>
</p>

<%= link_to 'Edit', edit_event_user_path(@event_user) %> |
<%= link_to 'Back', event_users_path %>