config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :event_users
  resources :event_foundations
  resources :events_users
  resources :foundation_types
  resources :profile_roles
  resources :profiles
  resources :roles
  resources :events
  devise_for :users
  resources :foundations
  get 'users/user'

  get 'admin/users'

  get 'home/index'
  
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_foundation.rb
class EventFoundation < ApplicationRecord
  belongs_to :foundation
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :event_foundation
  belongs_to :user
end

app/models/foundation.rb
class Foundation < ApplicationRecord
  belongs_to :foundation_type
end

app/models/foundation_type.rb
class FoundationType < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/profile_role.rb
class ProfileRole < ApplicationRecord
  belongs_to :role
  belongs_to :profile
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # attr_accessible :email, :password, :password_confirmation, :remember_me, :role_attributes
  has_one :role
  accepts_nested_attributes_for :role  
  
  validates :role_id, presence: true
end

app/controllers/foundation_types_controller.rb
class FoundationTypesController < ApplicationController
  before_action :set_foundation_type, only: [:show, :edit, :update, :destroy]

  # GET /foundation_types
  # GET /foundation_types.json
  def index
    @foundation_types = FoundationType.all
  end

  # GET /foundation_types/1
  # GET /foundation_types/1.json
  def show
  end

  # GET /foundation_types/new
  def new
    @foundation_type = FoundationType.new
  end

  # GET /foundation_types/1/edit
  def edit
  end

  # POST /foundation_types
  # POST /foundation_types.json
  def create
    @foundation_type = FoundationType.new(foundation_type_params)

    respond_to do |format|
      if @foundation_type.save
        format.html { redirect_to @foundation_type, notice: 'Foundation type was successfully created.' }
        format.json { render :show, status: :created, location: @foundation_type }
      else
        format.html { render :new }
        format.json { render json: @foundation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foundation_types/1
  # PATCH/PUT /foundation_types/1.json
  def update
    respond_to do |format|
      if @foundation_type.update(foundation_type_params)
        format.html { redirect_to @foundation_type, notice: 'Foundation type was successfully updated.' }
        format.json { render :show, status: :ok, location: @foundation_type }
      else
        format.html { render :edit }
        format.json { render json: @foundation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foundation_types/1
  # DELETE /foundation_types/1.json
  def destroy
    @foundation_type.destroy
    respond_to do |format|
      format.html { redirect_to foundation_types_url, notice: 'Foundation type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foundation_type
      @foundation_type = FoundationType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foundation_type_params
      params.require(:foundation_type).permit(:name, :description, :active)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/foundation_helper.rb
module FoundationHelper
end

app/helpers/foundation_types_helper.rb
module FoundationTypesHelper
end

app/helpers/foundations_helper.rb
module FoundationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foundation_types/_form.html.erb
<%= form_with(model: foundation_type, local: true) do |form| %>
  <% if foundation_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foundation_type.errors.count, "error") %> prohibited this foundation_type from being saved:</h2>

      <ul>
      <% foundation_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :foundation_type_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :foundation_type_description %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.number_field :active, id: :foundation_type_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foundation_types/edit.html.erb
<h1>Editing Foundation Type</h1>

<%= render 'form', foundation_type: @foundation_type %>

<%= link_to 'Show', @foundation_type %> |
<%= link_to 'Back', foundation_types_path %>

app/views/foundation_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foundation Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foundation_types.each do |foundation_type| %>
      <tr>
        <td><%= foundation_type.name %></td>
        <td><%= foundation_type.description %></td>
        <td><%= foundation_type.active %></td>
        <td><%= link_to 'Show', foundation_type %></td>
        <td><%= link_to 'Edit', edit_foundation_type_path(foundation_type) %></td>
        <td><%= link_to 'Destroy', foundation_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foundation Type', new_foundation_type_path %>

app/views/foundation_types/new.html.erb
<h1>New Foundation Type</h1>

<%= render 'form', foundation_type: @foundation_type %>

<%= link_to 'Back', foundation_types_path %>

app/views/foundation_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @foundation_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @foundation_type.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @foundation_type.active %>
</p>

<%= link_to 'Edit', edit_foundation_type_path(@foundation_type) %> |
<%= link_to 'Back', foundation_types_path %>