config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :event_users
  resources :event_foundations
  resources :events_users
  resources :foundation_types
  resources :profile_roles
  resources :profiles
  resources :roles
  resources :events
  devise_for :users
  resources :foundations
  get 'users/user'

  get 'admin/users'

  get 'home/index'
  
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_foundation.rb
class EventFoundation < ApplicationRecord
  belongs_to :foundation
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :event_foundation
  belongs_to :user
end

app/models/foundation.rb
class Foundation < ApplicationRecord
  belongs_to :foundation_type
end

app/models/foundation_type.rb
class FoundationType < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/profile_role.rb
class ProfileRole < ApplicationRecord
  belongs_to :role
  belongs_to :profile
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # attr_accessible :email, :password, :password_confirmation, :remember_me, :role_attributes
  has_one :role
  accepts_nested_attributes_for :role  
  
  validates :role_id, presence: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profile_roles_controller.rb
class ProfileRolesController < ApplicationController
  before_action :set_profile_role, only: [:show, :edit, :update, :destroy]

  # GET /profile_roles
  # GET /profile_roles.json
  def index
    @profile_roles = ProfileRole.all
  end

  # GET /profile_roles/1
  # GET /profile_roles/1.json
  def show
  end

  # GET /profile_roles/new
  def new
    @profile_role = ProfileRole.new
  end

  # GET /profile_roles/1/edit
  def edit
  end

  # POST /profile_roles
  # POST /profile_roles.json
  def create
    @profile_role = ProfileRole.new(profile_role_params)

    respond_to do |format|
      if @profile_role.save
        format.html { redirect_to @profile_role, notice: 'Profile role was successfully created.' }
        format.json { render :show, status: :created, location: @profile_role }
      else
        format.html { render :new }
        format.json { render json: @profile_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profile_roles/1
  # PATCH/PUT /profile_roles/1.json
  def update
    respond_to do |format|
      if @profile_role.update(profile_role_params)
        format.html { redirect_to @profile_role, notice: 'Profile role was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile_role }
      else
        format.html { render :edit }
        format.json { render json: @profile_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profile_roles/1
  # DELETE /profile_roles/1.json
  def destroy
    @profile_role.destroy
    respond_to do |format|
      format.html { redirect_to profile_roles_url, notice: 'Profile role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile_role
      @profile_role = ProfileRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_role_params
      params.require(:profile_role).permit(:role_id, :profile_id, :active)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/events_users_helper.rb
module EventsUsersHelper
end

app/helpers/foundation_helper.rb
module FoundationHelper
end

app/helpers/foundations_helper.rb
module FoundationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_roles_helper.rb
module ProfileRolesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/profile_roles/_form.html.erb
<%= form_with(model: profile_role, local: true) do |form| %>
  <% if profile_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile_role.errors.count, "error") %> prohibited this profile_role from being saved:</h2>

      <ul>
      <% profile_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :role_id %>
    <%= form.text_field :role_id, id: :profile_role_role_id %>
  </div>

  <div class="field">
    <%= form.label :profile_id %>
    <%= form.text_field :profile_id, id: :profile_role_profile_id %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.number_field :active, id: :profile_role_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profile_roles/edit.html.erb
<h1>Editing Profile Role</h1>

<%= render 'form', profile_role: @profile_role %>

<%= link_to 'Show', @profile_role %> |
<%= link_to 'Back', profile_roles_path %>

app/views/profile_roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profile Roles</h1>

<table>
  <thead>
    <tr>
      <th>Role</th>
      <th>Profile</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profile_roles.each do |profile_role| %>
      <tr>
        <td><%= profile_role.role %></td>
        <td><%= profile_role.profile %></td>
        <td><%= profile_role.active %></td>
        <td><%= link_to 'Show', profile_role %></td>
        <td><%= link_to 'Edit', edit_profile_role_path(profile_role) %></td>
        <td><%= link_to 'Destroy', profile_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile Role', new_profile_role_path %>

app/views/profile_roles/new.html.erb
<h1>New Profile Role</h1>

<%= render 'form', profile_role: @profile_role %>

<%= link_to 'Back', profile_roles_path %>

app/views/profile_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role:</strong>
  <%= @profile_role.role %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @profile_role.profile %>
</p>

<p>
  <strong>Active:</strong>
  <%= @profile_role.active %>
</p>

<%= link_to 'Edit', edit_profile_role_path(@profile_role) %> |
<%= link_to 'Back', profile_roles_path %>